### ISSUE TITLE
Linkage pay information with database

### ISSUE THREAD

**Issue by lojpark** [lojpark/dreamer#14]
Second form of Register component: PaymentRegisterForm

**Comment by TanDung2512** [comment]
finishing , some features are added : 
- New tab "profile" appeared on App Nav when successfully signing in
- Info payment , personal information automatically get from firebase and are showed in profile tab 
- fix bootstrap ( can be using it  as a component-scoped style )
- modify a little bit in register , when clicking to the final step , Creating account will happen ( payment is optional ) 
Needed to "npm react-bootstrap" to use bootstrap
