### ISSUE TITLE
Create posting form component (only layout)

### ISSUE THREAD

**Issue by lojpark** [lojpark/dreamer#5]
Refer this: https://reactjsexample.com/tag/editor/

**Comment by Joker195** [comment]
Refer this : https://v0.material-ui.com/#/components/card
and this one : https://reactjsexample.com/facebook-components-like-a-login-button-like-share-comments-page-or-embedded-post/
for loading post : https://reactjsexample.com/svg-component-to-create-placeholder-loading-like-facebook-cards-loading/
